version: '3'

services: 
  db:
    image: postgres
    environment:
      POSTGRES_USER: pt
      POSTGRES_PASSWORD: ${PGPW:-pt}
  api:
    depends_on: 
      - db
    build:
      context: ../
      dockerfile: Pt.Api/Dockerfile
    environment:
      - 'PT_API_ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=pt;User Id=${PGPW:-pt};Password=pt;'
  tests:
    depends_on: 
      - api
    build:
      context: ../
      dockerfile: Pt.Api.Acceptance.Tests/Dockerfile
    environment:
      - 'TEST_PT_API_API__URI=http://api'
