name: dev build & deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  IMAGE_NAME: project-tracker
  
jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the API Docker image
        working-directory: api
        run: docker build . --file Pt.Api/Dockerfile --tag $IMAGE_NAME-api --label "githash=${GITHUB_SHA::8}"

  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run dockerized API behaviour tests
        working-directory: api/Pt.Api.Acceptance.Tests/
        run: docker-compose run tests 
        
  ui-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the UI Docker image
        working-directory: ui/project-tracker
        run: docker build . --file Dockerfile --tag $IMAGE_NAME-ui --label "githash=${GITHUB_SHA::8}"
